// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task_operation.proto

package com.tianzhixing.kernel.grpc.proto.task.operation;

public final class TaskOperationServiceProto {
  private TaskOperationServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_task_operation_TaskInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_task_operation_TaskInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_task_operation_Result_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_task_operation_Result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024task_operation.proto\022\016task.operation\032\025" +
      "response_entity.proto\"V\n\010TaskInfo\022\024\n\014acc" +
      "ountToken\030\001 \001(\t\022\r\n\005token\030\002 \001(\t\022\016\n\006taskId" +
      "\030\003 \001(\t\022\025\n\roperationTime\030\004 \001(\003\"1\n\006Result\022" +
      "\'\n\016responseEntity\030\001 \001(\0132\017.ResponseEntity" +
      "2\222\001\n\024TaskOperationService\022<\n\006accept\022\030.ta" +
      "sk.operation.TaskInfo\032\026.task.operation.R" +
      "esult\"\000\022<\n\006cancel\022\030.task.operation.TaskI" +
      "nfo\032\026.task.operation.Result\"\000BO\n0com.tia" +
      "nzhixing.kernel.grpc.proto.task.operatio" +
      "nB\031TaskOperationServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tianzhixing.kernel.grpc.proto.ResponseEntityProto.getDescriptor(),
        }, assigner);
    internal_static_task_operation_TaskInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_task_operation_TaskInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_task_operation_TaskInfo_descriptor,
        new java.lang.String[] { "AccountToken", "Token", "TaskId", "OperationTime", });
    internal_static_task_operation_Result_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_task_operation_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_task_operation_Result_descriptor,
        new java.lang.String[] { "ResponseEntity", });
    com.tianzhixing.kernel.grpc.proto.ResponseEntityProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
