// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account_starpoint.proto

package com.tianzhixing.kernel.grpc.proto.account.starpoint;

/**
 * <pre>
 *流水查询条件
 * </pre>
 *
 * Protobuf type {@code account.starpoint.RecordsCondition}
 */
public  final class RecordsCondition extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:account.starpoint.RecordsCondition)
    RecordsConditionOrBuilder {
  // Use RecordsCondition.newBuilder() to construct.
  private RecordsCondition(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RecordsCondition() {
    accountToken_ = "";
    token_ = "";
    beginTime_ = 0L;
    endTime_ = 0L;
    taskId_ = "";
    advertisementId_ = "";
    recordsType_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private RecordsCondition(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            accountToken_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            token_ = s;
            break;
          }
          case 24: {

            beginTime_ = input.readInt64();
            break;
          }
          case 32: {

            endTime_ = input.readInt64();
            break;
          }
          case 42: {
            com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper.Builder subBuilder = null;
            if (pageMapper_ != null) {
              subBuilder = pageMapper_.toBuilder();
            }
            pageMapper_ = input.readMessage(com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pageMapper_);
              pageMapper_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            taskId_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            advertisementId_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            recordsType_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tianzhixing.kernel.grpc.proto.account.starpoint.AccountStarPointServiceProto.internal_static_account_starpoint_RecordsCondition_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tianzhixing.kernel.grpc.proto.account.starpoint.AccountStarPointServiceProto.internal_static_account_starpoint_RecordsCondition_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition.class, com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition.Builder.class);
  }

  public static final int ACCOUNTTOKEN_FIELD_NUMBER = 1;
  private volatile java.lang.Object accountToken_;
  /**
   * <pre>
   *需存储的第三方唯一token 必填
   * </pre>
   *
   * <code>optional string accountToken = 1;</code>
   */
  public java.lang.String getAccountToken() {
    java.lang.Object ref = accountToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accountToken_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *需存储的第三方唯一token 必填
   * </pre>
   *
   * <code>optional string accountToken = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAccountTokenBytes() {
    java.lang.Object ref = accountToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accountToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOKEN_FIELD_NUMBER = 2;
  private volatile java.lang.Object token_;
  /**
   * <pre>
   *安全校验码-必填
   * </pre>
   *
   * <code>optional string token = 2;</code>
   */
  public java.lang.String getToken() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      token_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *安全校验码-必填
   * </pre>
   *
   * <code>optional string token = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTokenBytes() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      token_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BEGINTIME_FIELD_NUMBER = 3;
  private long beginTime_;
  /**
   * <pre>
   *开始时间-选填
   * </pre>
   *
   * <code>optional int64 beginTime = 3;</code>
   */
  public long getBeginTime() {
    return beginTime_;
  }

  public static final int ENDTIME_FIELD_NUMBER = 4;
  private long endTime_;
  /**
   * <pre>
   *结束时间-选填
   * </pre>
   *
   * <code>optional int64 endTime = 4;</code>
   */
  public long getEndTime() {
    return endTime_;
  }

  public static final int PAGEMAPPER_FIELD_NUMBER = 5;
  private com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper pageMapper_;
  /**
   * <pre>
   *分页信息 必填
   * </pre>
   *
   * <code>optional .account.starpoint.PageMapper pageMapper = 5;</code>
   */
  public boolean hasPageMapper() {
    return pageMapper_ != null;
  }
  /**
   * <pre>
   *分页信息 必填
   * </pre>
   *
   * <code>optional .account.starpoint.PageMapper pageMapper = 5;</code>
   */
  public com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper getPageMapper() {
    return pageMapper_ == null ? com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper.getDefaultInstance() : pageMapper_;
  }
  /**
   * <pre>
   *分页信息 必填
   * </pre>
   *
   * <code>optional .account.starpoint.PageMapper pageMapper = 5;</code>
   */
  public com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapperOrBuilder getPageMapperOrBuilder() {
    return getPageMapper();
  }

  public static final int TASKID_FIELD_NUMBER = 6;
  private volatile java.lang.Object taskId_;
  /**
   * <pre>
   *任务ID - 选填
   * </pre>
   *
   * <code>optional string taskId = 6;</code>
   */
  public java.lang.String getTaskId() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      taskId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *任务ID - 选填
   * </pre>
   *
   * <code>optional string taskId = 6;</code>
   */
  public com.google.protobuf.ByteString
      getTaskIdBytes() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taskId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADVERTISEMENTID_FIELD_NUMBER = 7;
  private volatile java.lang.Object advertisementId_;
  /**
   * <pre>
   *广告ID - 选填
   * </pre>
   *
   * <code>optional string advertisementId = 7;</code>
   */
  public java.lang.String getAdvertisementId() {
    java.lang.Object ref = advertisementId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      advertisementId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *广告ID - 选填
   * </pre>
   *
   * <code>optional string advertisementId = 7;</code>
   */
  public com.google.protobuf.ByteString
      getAdvertisementIdBytes() {
    java.lang.Object ref = advertisementId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      advertisementId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECORDSTYPE_FIELD_NUMBER = 8;
  private volatile java.lang.Object recordsType_;
  /**
   * <pre>
   *记录类型 - 必填(ALL, TASK, ADVERTISEMENT, BASIC，RANDOM，CONSUME)
   * </pre>
   *
   * <code>optional string recordsType = 8;</code>
   */
  public java.lang.String getRecordsType() {
    java.lang.Object ref = recordsType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      recordsType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *记录类型 - 必填(ALL, TASK, ADVERTISEMENT, BASIC，RANDOM，CONSUME)
   * </pre>
   *
   * <code>optional string recordsType = 8;</code>
   */
  public com.google.protobuf.ByteString
      getRecordsTypeBytes() {
    java.lang.Object ref = recordsType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      recordsType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAccountTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accountToken_);
    }
    if (!getTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
    }
    if (beginTime_ != 0L) {
      output.writeInt64(3, beginTime_);
    }
    if (endTime_ != 0L) {
      output.writeInt64(4, endTime_);
    }
    if (pageMapper_ != null) {
      output.writeMessage(5, getPageMapper());
    }
    if (!getTaskIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, taskId_);
    }
    if (!getAdvertisementIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, advertisementId_);
    }
    if (!getRecordsTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, recordsType_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAccountTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accountToken_);
    }
    if (!getTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
    }
    if (beginTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, beginTime_);
    }
    if (endTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, endTime_);
    }
    if (pageMapper_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getPageMapper());
    }
    if (!getTaskIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, taskId_);
    }
    if (!getAdvertisementIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, advertisementId_);
    }
    if (!getRecordsTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, recordsType_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition)) {
      return super.equals(obj);
    }
    com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition other = (com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition) obj;

    boolean result = true;
    result = result && getAccountToken()
        .equals(other.getAccountToken());
    result = result && getToken()
        .equals(other.getToken());
    result = result && (getBeginTime()
        == other.getBeginTime());
    result = result && (getEndTime()
        == other.getEndTime());
    result = result && (hasPageMapper() == other.hasPageMapper());
    if (hasPageMapper()) {
      result = result && getPageMapper()
          .equals(other.getPageMapper());
    }
    result = result && getTaskId()
        .equals(other.getTaskId());
    result = result && getAdvertisementId()
        .equals(other.getAdvertisementId());
    result = result && getRecordsType()
        .equals(other.getRecordsType());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ACCOUNTTOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getAccountToken().hashCode();
    hash = (37 * hash) + TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getToken().hashCode();
    hash = (37 * hash) + BEGINTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBeginTime());
    hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndTime());
    if (hasPageMapper()) {
      hash = (37 * hash) + PAGEMAPPER_FIELD_NUMBER;
      hash = (53 * hash) + getPageMapper().hashCode();
    }
    hash = (37 * hash) + TASKID_FIELD_NUMBER;
    hash = (53 * hash) + getTaskId().hashCode();
    hash = (37 * hash) + ADVERTISEMENTID_FIELD_NUMBER;
    hash = (53 * hash) + getAdvertisementId().hashCode();
    hash = (37 * hash) + RECORDSTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getRecordsType().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *流水查询条件
   * </pre>
   *
   * Protobuf type {@code account.starpoint.RecordsCondition}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:account.starpoint.RecordsCondition)
      com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsConditionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tianzhixing.kernel.grpc.proto.account.starpoint.AccountStarPointServiceProto.internal_static_account_starpoint_RecordsCondition_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tianzhixing.kernel.grpc.proto.account.starpoint.AccountStarPointServiceProto.internal_static_account_starpoint_RecordsCondition_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition.class, com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition.Builder.class);
    }

    // Construct using com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      accountToken_ = "";

      token_ = "";

      beginTime_ = 0L;

      endTime_ = 0L;

      if (pageMapperBuilder_ == null) {
        pageMapper_ = null;
      } else {
        pageMapper_ = null;
        pageMapperBuilder_ = null;
      }
      taskId_ = "";

      advertisementId_ = "";

      recordsType_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tianzhixing.kernel.grpc.proto.account.starpoint.AccountStarPointServiceProto.internal_static_account_starpoint_RecordsCondition_descriptor;
    }

    public com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition getDefaultInstanceForType() {
      return com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition.getDefaultInstance();
    }

    public com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition build() {
      com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition buildPartial() {
      com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition result = new com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition(this);
      result.accountToken_ = accountToken_;
      result.token_ = token_;
      result.beginTime_ = beginTime_;
      result.endTime_ = endTime_;
      if (pageMapperBuilder_ == null) {
        result.pageMapper_ = pageMapper_;
      } else {
        result.pageMapper_ = pageMapperBuilder_.build();
      }
      result.taskId_ = taskId_;
      result.advertisementId_ = advertisementId_;
      result.recordsType_ = recordsType_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition) {
        return mergeFrom((com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition other) {
      if (other == com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition.getDefaultInstance()) return this;
      if (!other.getAccountToken().isEmpty()) {
        accountToken_ = other.accountToken_;
        onChanged();
      }
      if (!other.getToken().isEmpty()) {
        token_ = other.token_;
        onChanged();
      }
      if (other.getBeginTime() != 0L) {
        setBeginTime(other.getBeginTime());
      }
      if (other.getEndTime() != 0L) {
        setEndTime(other.getEndTime());
      }
      if (other.hasPageMapper()) {
        mergePageMapper(other.getPageMapper());
      }
      if (!other.getTaskId().isEmpty()) {
        taskId_ = other.taskId_;
        onChanged();
      }
      if (!other.getAdvertisementId().isEmpty()) {
        advertisementId_ = other.advertisementId_;
        onChanged();
      }
      if (!other.getRecordsType().isEmpty()) {
        recordsType_ = other.recordsType_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object accountToken_ = "";
    /**
     * <pre>
     *需存储的第三方唯一token 必填
     * </pre>
     *
     * <code>optional string accountToken = 1;</code>
     */
    public java.lang.String getAccountToken() {
      java.lang.Object ref = accountToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *需存储的第三方唯一token 必填
     * </pre>
     *
     * <code>optional string accountToken = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAccountTokenBytes() {
      java.lang.Object ref = accountToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *需存储的第三方唯一token 必填
     * </pre>
     *
     * <code>optional string accountToken = 1;</code>
     */
    public Builder setAccountToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accountToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *需存储的第三方唯一token 必填
     * </pre>
     *
     * <code>optional string accountToken = 1;</code>
     */
    public Builder clearAccountToken() {
      
      accountToken_ = getDefaultInstance().getAccountToken();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *需存储的第三方唯一token 必填
     * </pre>
     *
     * <code>optional string accountToken = 1;</code>
     */
    public Builder setAccountTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accountToken_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object token_ = "";
    /**
     * <pre>
     *安全校验码-必填
     * </pre>
     *
     * <code>optional string token = 2;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *安全校验码-必填
     * </pre>
     *
     * <code>optional string token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *安全校验码-必填
     * </pre>
     *
     * <code>optional string token = 2;</code>
     */
    public Builder setToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      token_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *安全校验码-必填
     * </pre>
     *
     * <code>optional string token = 2;</code>
     */
    public Builder clearToken() {
      
      token_ = getDefaultInstance().getToken();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *安全校验码-必填
     * </pre>
     *
     * <code>optional string token = 2;</code>
     */
    public Builder setTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      token_ = value;
      onChanged();
      return this;
    }

    private long beginTime_ ;
    /**
     * <pre>
     *开始时间-选填
     * </pre>
     *
     * <code>optional int64 beginTime = 3;</code>
     */
    public long getBeginTime() {
      return beginTime_;
    }
    /**
     * <pre>
     *开始时间-选填
     * </pre>
     *
     * <code>optional int64 beginTime = 3;</code>
     */
    public Builder setBeginTime(long value) {
      
      beginTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *开始时间-选填
     * </pre>
     *
     * <code>optional int64 beginTime = 3;</code>
     */
    public Builder clearBeginTime() {
      
      beginTime_ = 0L;
      onChanged();
      return this;
    }

    private long endTime_ ;
    /**
     * <pre>
     *结束时间-选填
     * </pre>
     *
     * <code>optional int64 endTime = 4;</code>
     */
    public long getEndTime() {
      return endTime_;
    }
    /**
     * <pre>
     *结束时间-选填
     * </pre>
     *
     * <code>optional int64 endTime = 4;</code>
     */
    public Builder setEndTime(long value) {
      
      endTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *结束时间-选填
     * </pre>
     *
     * <code>optional int64 endTime = 4;</code>
     */
    public Builder clearEndTime() {
      
      endTime_ = 0L;
      onChanged();
      return this;
    }

    private com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper pageMapper_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper, com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper.Builder, com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapperOrBuilder> pageMapperBuilder_;
    /**
     * <pre>
     *分页信息 必填
     * </pre>
     *
     * <code>optional .account.starpoint.PageMapper pageMapper = 5;</code>
     */
    public boolean hasPageMapper() {
      return pageMapperBuilder_ != null || pageMapper_ != null;
    }
    /**
     * <pre>
     *分页信息 必填
     * </pre>
     *
     * <code>optional .account.starpoint.PageMapper pageMapper = 5;</code>
     */
    public com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper getPageMapper() {
      if (pageMapperBuilder_ == null) {
        return pageMapper_ == null ? com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper.getDefaultInstance() : pageMapper_;
      } else {
        return pageMapperBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *分页信息 必填
     * </pre>
     *
     * <code>optional .account.starpoint.PageMapper pageMapper = 5;</code>
     */
    public Builder setPageMapper(com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper value) {
      if (pageMapperBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pageMapper_ = value;
        onChanged();
      } else {
        pageMapperBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *分页信息 必填
     * </pre>
     *
     * <code>optional .account.starpoint.PageMapper pageMapper = 5;</code>
     */
    public Builder setPageMapper(
        com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper.Builder builderForValue) {
      if (pageMapperBuilder_ == null) {
        pageMapper_ = builderForValue.build();
        onChanged();
      } else {
        pageMapperBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *分页信息 必填
     * </pre>
     *
     * <code>optional .account.starpoint.PageMapper pageMapper = 5;</code>
     */
    public Builder mergePageMapper(com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper value) {
      if (pageMapperBuilder_ == null) {
        if (pageMapper_ != null) {
          pageMapper_ =
            com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper.newBuilder(pageMapper_).mergeFrom(value).buildPartial();
        } else {
          pageMapper_ = value;
        }
        onChanged();
      } else {
        pageMapperBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *分页信息 必填
     * </pre>
     *
     * <code>optional .account.starpoint.PageMapper pageMapper = 5;</code>
     */
    public Builder clearPageMapper() {
      if (pageMapperBuilder_ == null) {
        pageMapper_ = null;
        onChanged();
      } else {
        pageMapper_ = null;
        pageMapperBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *分页信息 必填
     * </pre>
     *
     * <code>optional .account.starpoint.PageMapper pageMapper = 5;</code>
     */
    public com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper.Builder getPageMapperBuilder() {
      
      onChanged();
      return getPageMapperFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *分页信息 必填
     * </pre>
     *
     * <code>optional .account.starpoint.PageMapper pageMapper = 5;</code>
     */
    public com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapperOrBuilder getPageMapperOrBuilder() {
      if (pageMapperBuilder_ != null) {
        return pageMapperBuilder_.getMessageOrBuilder();
      } else {
        return pageMapper_ == null ?
            com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper.getDefaultInstance() : pageMapper_;
      }
    }
    /**
     * <pre>
     *分页信息 必填
     * </pre>
     *
     * <code>optional .account.starpoint.PageMapper pageMapper = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper, com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper.Builder, com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapperOrBuilder> 
        getPageMapperFieldBuilder() {
      if (pageMapperBuilder_ == null) {
        pageMapperBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper, com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper.Builder, com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapperOrBuilder>(
                getPageMapper(),
                getParentForChildren(),
                isClean());
        pageMapper_ = null;
      }
      return pageMapperBuilder_;
    }

    private java.lang.Object taskId_ = "";
    /**
     * <pre>
     *任务ID - 选填
     * </pre>
     *
     * <code>optional string taskId = 6;</code>
     */
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *任务ID - 选填
     * </pre>
     *
     * <code>optional string taskId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *任务ID - 选填
     * </pre>
     *
     * <code>optional string taskId = 6;</code>
     */
    public Builder setTaskId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      taskId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *任务ID - 选填
     * </pre>
     *
     * <code>optional string taskId = 6;</code>
     */
    public Builder clearTaskId() {
      
      taskId_ = getDefaultInstance().getTaskId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *任务ID - 选填
     * </pre>
     *
     * <code>optional string taskId = 6;</code>
     */
    public Builder setTaskIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      taskId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object advertisementId_ = "";
    /**
     * <pre>
     *广告ID - 选填
     * </pre>
     *
     * <code>optional string advertisementId = 7;</code>
     */
    public java.lang.String getAdvertisementId() {
      java.lang.Object ref = advertisementId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        advertisementId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *广告ID - 选填
     * </pre>
     *
     * <code>optional string advertisementId = 7;</code>
     */
    public com.google.protobuf.ByteString
        getAdvertisementIdBytes() {
      java.lang.Object ref = advertisementId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        advertisementId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *广告ID - 选填
     * </pre>
     *
     * <code>optional string advertisementId = 7;</code>
     */
    public Builder setAdvertisementId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      advertisementId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *广告ID - 选填
     * </pre>
     *
     * <code>optional string advertisementId = 7;</code>
     */
    public Builder clearAdvertisementId() {
      
      advertisementId_ = getDefaultInstance().getAdvertisementId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *广告ID - 选填
     * </pre>
     *
     * <code>optional string advertisementId = 7;</code>
     */
    public Builder setAdvertisementIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      advertisementId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object recordsType_ = "";
    /**
     * <pre>
     *记录类型 - 必填(ALL, TASK, ADVERTISEMENT, BASIC，RANDOM，CONSUME)
     * </pre>
     *
     * <code>optional string recordsType = 8;</code>
     */
    public java.lang.String getRecordsType() {
      java.lang.Object ref = recordsType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recordsType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *记录类型 - 必填(ALL, TASK, ADVERTISEMENT, BASIC，RANDOM，CONSUME)
     * </pre>
     *
     * <code>optional string recordsType = 8;</code>
     */
    public com.google.protobuf.ByteString
        getRecordsTypeBytes() {
      java.lang.Object ref = recordsType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recordsType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *记录类型 - 必填(ALL, TASK, ADVERTISEMENT, BASIC，RANDOM，CONSUME)
     * </pre>
     *
     * <code>optional string recordsType = 8;</code>
     */
    public Builder setRecordsType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      recordsType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *记录类型 - 必填(ALL, TASK, ADVERTISEMENT, BASIC，RANDOM，CONSUME)
     * </pre>
     *
     * <code>optional string recordsType = 8;</code>
     */
    public Builder clearRecordsType() {
      
      recordsType_ = getDefaultInstance().getRecordsType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *记录类型 - 必填(ALL, TASK, ADVERTISEMENT, BASIC，RANDOM，CONSUME)
     * </pre>
     *
     * <code>optional string recordsType = 8;</code>
     */
    public Builder setRecordsTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      recordsType_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:account.starpoint.RecordsCondition)
  }

  // @@protoc_insertion_point(class_scope:account.starpoint.RecordsCondition)
  private static final com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition();
  }

  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RecordsCondition>
      PARSER = new com.google.protobuf.AbstractParser<RecordsCondition>() {
    public RecordsCondition parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new RecordsCondition(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RecordsCondition> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RecordsCondition> getParserForType() {
    return PARSER;
  }

  public com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsCondition getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

