// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account_starpoint.proto

package com.tianzhixing.kernel.grpc.proto.account.starpoint;

public interface RecordsWithDayInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:account.starpoint.RecordsWithDayInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *操作星点数
   * </pre>
   *
   * <code>optional string starPoint = 1;</code>
   */
  java.lang.String getStarPoint();
  /**
   * <pre>
   *操作星点数
   * </pre>
   *
   * <code>optional string starPoint = 1;</code>
   */
  com.google.protobuf.ByteString
      getStarPointBytes();

  /**
   * <pre>
   *日期(yyyyMMdd)
   * </pre>
   *
   * <code>optional string date = 2;</code>
   */
  java.lang.String getDate();
  /**
   * <pre>
   *日期(yyyyMMdd)
   * </pre>
   *
   * <code>optional string date = 2;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();
}
