// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account_starpoint.proto

package com.tianzhixing.kernel.grpc.proto.account.starpoint;

public interface RecordsWithDayResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:account.starpoint.RecordsWithDayResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *记录
   * </pre>
   *
   * <code>repeated .account.starpoint.RecordsWithDayInfo records = 1;</code>
   */
  java.util.List<com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsWithDayInfo> 
      getRecordsList();
  /**
   * <pre>
   *记录
   * </pre>
   *
   * <code>repeated .account.starpoint.RecordsWithDayInfo records = 1;</code>
   */
  com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsWithDayInfo getRecords(int index);
  /**
   * <pre>
   *记录
   * </pre>
   *
   * <code>repeated .account.starpoint.RecordsWithDayInfo records = 1;</code>
   */
  int getRecordsCount();
  /**
   * <pre>
   *记录
   * </pre>
   *
   * <code>repeated .account.starpoint.RecordsWithDayInfo records = 1;</code>
   */
  java.util.List<? extends com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsWithDayInfoOrBuilder> 
      getRecordsOrBuilderList();
  /**
   * <pre>
   *记录
   * </pre>
   *
   * <code>repeated .account.starpoint.RecordsWithDayInfo records = 1;</code>
   */
  com.tianzhixing.kernel.grpc.proto.account.starpoint.RecordsWithDayInfoOrBuilder getRecordsOrBuilder(
      int index);

  /**
   * <code>optional .ResponseEntity responseEntity = 3;</code>
   */
  boolean hasResponseEntity();
  /**
   * <code>optional .ResponseEntity responseEntity = 3;</code>
   */
  com.tianzhixing.kernel.grpc.proto.ResponseEntity getResponseEntity();
  /**
   * <code>optional .ResponseEntity responseEntity = 3;</code>
   */
  com.tianzhixing.kernel.grpc.proto.ResponseEntityOrBuilder getResponseEntityOrBuilder();
}
