// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account_starpoint.proto

package com.tianzhixing.kernel.grpc.proto.account.starpoint;

/**
 * <pre>
 *根据任务查询用户采集的星点数结果详情
 * </pre>
 *
 * Protobuf type {@code account.starpoint.StarPointWithTaskResultDetail}
 */
public  final class StarPointWithTaskResultDetail extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:account.starpoint.StarPointWithTaskResultDetail)
    StarPointWithTaskResultDetailOrBuilder {
  // Use StarPointWithTaskResultDetail.newBuilder() to construct.
  private StarPointWithTaskResultDetail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StarPointWithTaskResultDetail() {
    starPoint_ = "";
    taskId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private StarPointWithTaskResultDetail(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            starPoint_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            taskId_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tianzhixing.kernel.grpc.proto.account.starpoint.AccountStarPointServiceProto.internal_static_account_starpoint_StarPointWithTaskResultDetail_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tianzhixing.kernel.grpc.proto.account.starpoint.AccountStarPointServiceProto.internal_static_account_starpoint_StarPointWithTaskResultDetail_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail.class, com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail.Builder.class);
  }

  public static final int STARPOINT_FIELD_NUMBER = 1;
  private volatile java.lang.Object starPoint_;
  /**
   * <pre>
   *星点数
   * </pre>
   *
   * <code>optional string starPoint = 1;</code>
   */
  public java.lang.String getStarPoint() {
    java.lang.Object ref = starPoint_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      starPoint_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *星点数
   * </pre>
   *
   * <code>optional string starPoint = 1;</code>
   */
  public com.google.protobuf.ByteString
      getStarPointBytes() {
    java.lang.Object ref = starPoint_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      starPoint_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TASKID_FIELD_NUMBER = 2;
  private volatile java.lang.Object taskId_;
  /**
   * <pre>
   *任务ID
   * </pre>
   *
   * <code>optional string taskId = 2;</code>
   */
  public java.lang.String getTaskId() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      taskId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *任务ID
   * </pre>
   *
   * <code>optional string taskId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTaskIdBytes() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taskId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getStarPointBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, starPoint_);
    }
    if (!getTaskIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, taskId_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getStarPointBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, starPoint_);
    }
    if (!getTaskIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, taskId_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail)) {
      return super.equals(obj);
    }
    com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail other = (com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail) obj;

    boolean result = true;
    result = result && getStarPoint()
        .equals(other.getStarPoint());
    result = result && getTaskId()
        .equals(other.getTaskId());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + STARPOINT_FIELD_NUMBER;
    hash = (53 * hash) + getStarPoint().hashCode();
    hash = (37 * hash) + TASKID_FIELD_NUMBER;
    hash = (53 * hash) + getTaskId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *根据任务查询用户采集的星点数结果详情
   * </pre>
   *
   * Protobuf type {@code account.starpoint.StarPointWithTaskResultDetail}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:account.starpoint.StarPointWithTaskResultDetail)
      com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetailOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tianzhixing.kernel.grpc.proto.account.starpoint.AccountStarPointServiceProto.internal_static_account_starpoint_StarPointWithTaskResultDetail_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tianzhixing.kernel.grpc.proto.account.starpoint.AccountStarPointServiceProto.internal_static_account_starpoint_StarPointWithTaskResultDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail.class, com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail.Builder.class);
    }

    // Construct using com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      starPoint_ = "";

      taskId_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tianzhixing.kernel.grpc.proto.account.starpoint.AccountStarPointServiceProto.internal_static_account_starpoint_StarPointWithTaskResultDetail_descriptor;
    }

    public com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail getDefaultInstanceForType() {
      return com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail.getDefaultInstance();
    }

    public com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail build() {
      com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail buildPartial() {
      com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail result = new com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail(this);
      result.starPoint_ = starPoint_;
      result.taskId_ = taskId_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail) {
        return mergeFrom((com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail other) {
      if (other == com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail.getDefaultInstance()) return this;
      if (!other.getStarPoint().isEmpty()) {
        starPoint_ = other.starPoint_;
        onChanged();
      }
      if (!other.getTaskId().isEmpty()) {
        taskId_ = other.taskId_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object starPoint_ = "";
    /**
     * <pre>
     *星点数
     * </pre>
     *
     * <code>optional string starPoint = 1;</code>
     */
    public java.lang.String getStarPoint() {
      java.lang.Object ref = starPoint_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        starPoint_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *星点数
     * </pre>
     *
     * <code>optional string starPoint = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStarPointBytes() {
      java.lang.Object ref = starPoint_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        starPoint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *星点数
     * </pre>
     *
     * <code>optional string starPoint = 1;</code>
     */
    public Builder setStarPoint(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      starPoint_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *星点数
     * </pre>
     *
     * <code>optional string starPoint = 1;</code>
     */
    public Builder clearStarPoint() {
      
      starPoint_ = getDefaultInstance().getStarPoint();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *星点数
     * </pre>
     *
     * <code>optional string starPoint = 1;</code>
     */
    public Builder setStarPointBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      starPoint_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object taskId_ = "";
    /**
     * <pre>
     *任务ID
     * </pre>
     *
     * <code>optional string taskId = 2;</code>
     */
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *任务ID
     * </pre>
     *
     * <code>optional string taskId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *任务ID
     * </pre>
     *
     * <code>optional string taskId = 2;</code>
     */
    public Builder setTaskId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      taskId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *任务ID
     * </pre>
     *
     * <code>optional string taskId = 2;</code>
     */
    public Builder clearTaskId() {
      
      taskId_ = getDefaultInstance().getTaskId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *任务ID
     * </pre>
     *
     * <code>optional string taskId = 2;</code>
     */
    public Builder setTaskIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      taskId_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:account.starpoint.StarPointWithTaskResultDetail)
  }

  // @@protoc_insertion_point(class_scope:account.starpoint.StarPointWithTaskResultDetail)
  private static final com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail();
  }

  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StarPointWithTaskResultDetail>
      PARSER = new com.google.protobuf.AbstractParser<StarPointWithTaskResultDetail>() {
    public StarPointWithTaskResultDetail parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new StarPointWithTaskResultDetail(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StarPointWithTaskResultDetail> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StarPointWithTaskResultDetail> getParserForType() {
    return PARSER;
  }

  public com.tianzhixing.kernel.grpc.proto.account.starpoint.StarPointWithTaskResultDetail getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

