// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IDCardAuthService.proto

package com.tianzhixing.auth.grpc.proto.idcard;

public interface IDCardInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:idcard.IDCardInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *名字
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   *名字
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *身份证件号码
   * </pre>
   *
   * <code>string idcard = 2;</code>
   */
  java.lang.String getIdcard();
  /**
   * <pre>
   *身份证件号码
   * </pre>
   *
   * <code>string idcard = 2;</code>
   */
  com.google.protobuf.ByteString
      getIdcardBytes();

  /**
   * <pre>
   *平台token
   * </pre>
   *
   * <code>string token = 3;</code>
   */
  java.lang.String getToken();
  /**
   * <pre>
   *平台token
   * </pre>
   *
   * <code>string token = 3;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
