// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device_operation.proto

package com.tianzhixing.kernel.grpc.proto.device.operation;

public interface DeviceInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:device.operation.DeviceInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *accountToken-必填
   * </pre>
   *
   * <code>optional string accountToken = 1;</code>
   */
  java.lang.String getAccountToken();
  /**
   * <pre>
   *accountToken-必填
   * </pre>
   *
   * <code>optional string accountToken = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccountTokenBytes();

  /**
   * <pre>
   *安全校验码-必填
   * </pre>
   *
   * <code>optional string token = 2;</code>
   */
  java.lang.String getToken();
  /**
   * <pre>
   *安全校验码-必填
   * </pre>
   *
   * <code>optional string token = 2;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <pre>
   *设备ID-必填
   * </pre>
   *
   * <code>optional string deviceId = 3;</code>
   */
  java.lang.String getDeviceId();
  /**
   * <pre>
   *设备ID-必填
   * </pre>
   *
   * <code>optional string deviceId = 3;</code>
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <pre>
   *设备类型 - 必填
   * </pre>
   *
   * <code>optional string deviceType = 4;</code>
   */
  java.lang.String getDeviceType();
  /**
   * <pre>
   *设备类型 - 必填
   * </pre>
   *
   * <code>optional string deviceType = 4;</code>
   */
  com.google.protobuf.ByteString
      getDeviceTypeBytes();

  /**
   * <pre>
   *设备MAC地址 - 必填
   * </pre>
   *
   * <code>optional string deviceMAC = 5;</code>
   */
  java.lang.String getDeviceMAC();
  /**
   * <pre>
   *设备MAC地址 - 必填
   * </pre>
   *
   * <code>optional string deviceMAC = 5;</code>
   */
  com.google.protobuf.ByteString
      getDeviceMACBytes();

  /**
   * <pre>
   *设备型号 - 必填
   * </pre>
   *
   * <code>optional string deviceModel = 6;</code>
   */
  java.lang.String getDeviceModel();
  /**
   * <pre>
   *设备型号 - 必填
   * </pre>
   *
   * <code>optional string deviceModel = 6;</code>
   */
  com.google.protobuf.ByteString
      getDeviceModelBytes();

  /**
   * <pre>
   *绑定时间 - 必填
   * </pre>
   *
   * <code>optional int64 operationTime = 7;</code>
   */
  long getOperationTime();
}
