// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MobileValidationService.proto

package com.tianzhixing.auth.grpc.proto.mobile;

/**
 * Protobuf type {@code mobile.CodeInfo}
 */
public  final class CodeInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mobile.CodeInfo)
    CodeInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CodeInfo.newBuilder() to construct.
  private CodeInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CodeInfo() {
    status_ = false;
    validationCode_ = "";
    senderOrg_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CodeInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            status_ = input.readBool();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            validationCode_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            senderOrg_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tianzhixing.auth.grpc.proto.mobile.MobileValidationProto.internal_static_mobile_CodeInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tianzhixing.auth.grpc.proto.mobile.MobileValidationProto.internal_static_mobile_CodeInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tianzhixing.auth.grpc.proto.mobile.CodeInfo.class, com.tianzhixing.auth.grpc.proto.mobile.CodeInfo.Builder.class);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private boolean status_;
  /**
   * <pre>
   *状态
   * </pre>
   *
   * <code>bool status = 1;</code>
   */
  public boolean getStatus() {
    return status_;
  }

  public static final int VALIDATIONCODE_FIELD_NUMBER = 2;
  private volatile java.lang.Object validationCode_;
  /**
   * <pre>
   *验证码
   * </pre>
   *
   * <code>string validationCode = 2;</code>
   */
  public java.lang.String getValidationCode() {
    java.lang.Object ref = validationCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      validationCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *验证码
   * </pre>
   *
   * <code>string validationCode = 2;</code>
   */
  public com.google.protobuf.ByteString
      getValidationCodeBytes() {
    java.lang.Object ref = validationCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      validationCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SENDERORG_FIELD_NUMBER = 3;
  private volatile java.lang.Object senderOrg_;
  /**
   * <pre>
   * 发送机构
   * </pre>
   *
   * <code>string senderOrg = 3;</code>
   */
  public java.lang.String getSenderOrg() {
    java.lang.Object ref = senderOrg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      senderOrg_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 发送机构
   * </pre>
   *
   * <code>string senderOrg = 3;</code>
   */
  public com.google.protobuf.ByteString
      getSenderOrgBytes() {
    java.lang.Object ref = senderOrg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      senderOrg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != false) {
      output.writeBool(1, status_);
    }
    if (!getValidationCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, validationCode_);
    }
    if (!getSenderOrgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, senderOrg_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, status_);
    }
    if (!getValidationCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, validationCode_);
    }
    if (!getSenderOrgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, senderOrg_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tianzhixing.auth.grpc.proto.mobile.CodeInfo)) {
      return super.equals(obj);
    }
    com.tianzhixing.auth.grpc.proto.mobile.CodeInfo other = (com.tianzhixing.auth.grpc.proto.mobile.CodeInfo) obj;

    boolean result = true;
    result = result && (getStatus()
        == other.getStatus());
    result = result && getValidationCode()
        .equals(other.getValidationCode());
    result = result && getSenderOrg()
        .equals(other.getSenderOrg());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getStatus());
    hash = (37 * hash) + VALIDATIONCODE_FIELD_NUMBER;
    hash = (53 * hash) + getValidationCode().hashCode();
    hash = (37 * hash) + SENDERORG_FIELD_NUMBER;
    hash = (53 * hash) + getSenderOrg().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tianzhixing.auth.grpc.proto.mobile.CodeInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tianzhixing.auth.grpc.proto.mobile.CodeInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tianzhixing.auth.grpc.proto.mobile.CodeInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tianzhixing.auth.grpc.proto.mobile.CodeInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tianzhixing.auth.grpc.proto.mobile.CodeInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tianzhixing.auth.grpc.proto.mobile.CodeInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tianzhixing.auth.grpc.proto.mobile.CodeInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tianzhixing.auth.grpc.proto.mobile.CodeInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tianzhixing.auth.grpc.proto.mobile.CodeInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tianzhixing.auth.grpc.proto.mobile.CodeInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tianzhixing.auth.grpc.proto.mobile.CodeInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tianzhixing.auth.grpc.proto.mobile.CodeInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tianzhixing.auth.grpc.proto.mobile.CodeInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mobile.CodeInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mobile.CodeInfo)
      com.tianzhixing.auth.grpc.proto.mobile.CodeInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tianzhixing.auth.grpc.proto.mobile.MobileValidationProto.internal_static_mobile_CodeInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tianzhixing.auth.grpc.proto.mobile.MobileValidationProto.internal_static_mobile_CodeInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tianzhixing.auth.grpc.proto.mobile.CodeInfo.class, com.tianzhixing.auth.grpc.proto.mobile.CodeInfo.Builder.class);
    }

    // Construct using com.tianzhixing.auth.grpc.proto.mobile.CodeInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      status_ = false;

      validationCode_ = "";

      senderOrg_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tianzhixing.auth.grpc.proto.mobile.MobileValidationProto.internal_static_mobile_CodeInfo_descriptor;
    }

    @java.lang.Override
    public com.tianzhixing.auth.grpc.proto.mobile.CodeInfo getDefaultInstanceForType() {
      return com.tianzhixing.auth.grpc.proto.mobile.CodeInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.tianzhixing.auth.grpc.proto.mobile.CodeInfo build() {
      com.tianzhixing.auth.grpc.proto.mobile.CodeInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tianzhixing.auth.grpc.proto.mobile.CodeInfo buildPartial() {
      com.tianzhixing.auth.grpc.proto.mobile.CodeInfo result = new com.tianzhixing.auth.grpc.proto.mobile.CodeInfo(this);
      result.status_ = status_;
      result.validationCode_ = validationCode_;
      result.senderOrg_ = senderOrg_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tianzhixing.auth.grpc.proto.mobile.CodeInfo) {
        return mergeFrom((com.tianzhixing.auth.grpc.proto.mobile.CodeInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tianzhixing.auth.grpc.proto.mobile.CodeInfo other) {
      if (other == com.tianzhixing.auth.grpc.proto.mobile.CodeInfo.getDefaultInstance()) return this;
      if (other.getStatus() != false) {
        setStatus(other.getStatus());
      }
      if (!other.getValidationCode().isEmpty()) {
        validationCode_ = other.validationCode_;
        onChanged();
      }
      if (!other.getSenderOrg().isEmpty()) {
        senderOrg_ = other.senderOrg_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tianzhixing.auth.grpc.proto.mobile.CodeInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tianzhixing.auth.grpc.proto.mobile.CodeInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean status_ ;
    /**
     * <pre>
     *状态
     * </pre>
     *
     * <code>bool status = 1;</code>
     */
    public boolean getStatus() {
      return status_;
    }
    /**
     * <pre>
     *状态
     * </pre>
     *
     * <code>bool status = 1;</code>
     */
    public Builder setStatus(boolean value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *状态
     * </pre>
     *
     * <code>bool status = 1;</code>
     */
    public Builder clearStatus() {
      
      status_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object validationCode_ = "";
    /**
     * <pre>
     *验证码
     * </pre>
     *
     * <code>string validationCode = 2;</code>
     */
    public java.lang.String getValidationCode() {
      java.lang.Object ref = validationCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        validationCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *验证码
     * </pre>
     *
     * <code>string validationCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValidationCodeBytes() {
      java.lang.Object ref = validationCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        validationCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *验证码
     * </pre>
     *
     * <code>string validationCode = 2;</code>
     */
    public Builder setValidationCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      validationCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *验证码
     * </pre>
     *
     * <code>string validationCode = 2;</code>
     */
    public Builder clearValidationCode() {
      
      validationCode_ = getDefaultInstance().getValidationCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *验证码
     * </pre>
     *
     * <code>string validationCode = 2;</code>
     */
    public Builder setValidationCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      validationCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object senderOrg_ = "";
    /**
     * <pre>
     * 发送机构
     * </pre>
     *
     * <code>string senderOrg = 3;</code>
     */
    public java.lang.String getSenderOrg() {
      java.lang.Object ref = senderOrg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderOrg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 发送机构
     * </pre>
     *
     * <code>string senderOrg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSenderOrgBytes() {
      java.lang.Object ref = senderOrg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderOrg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 发送机构
     * </pre>
     *
     * <code>string senderOrg = 3;</code>
     */
    public Builder setSenderOrg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      senderOrg_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发送机构
     * </pre>
     *
     * <code>string senderOrg = 3;</code>
     */
    public Builder clearSenderOrg() {
      
      senderOrg_ = getDefaultInstance().getSenderOrg();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发送机构
     * </pre>
     *
     * <code>string senderOrg = 3;</code>
     */
    public Builder setSenderOrgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      senderOrg_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mobile.CodeInfo)
  }

  // @@protoc_insertion_point(class_scope:mobile.CodeInfo)
  private static final com.tianzhixing.auth.grpc.proto.mobile.CodeInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tianzhixing.auth.grpc.proto.mobile.CodeInfo();
  }

  public static com.tianzhixing.auth.grpc.proto.mobile.CodeInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CodeInfo>
      PARSER = new com.google.protobuf.AbstractParser<CodeInfo>() {
    @java.lang.Override
    public CodeInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CodeInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CodeInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CodeInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tianzhixing.auth.grpc.proto.mobile.CodeInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

