// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MobileValidationService.proto

package com.tianzhixing.auth.grpc.proto.mobile;

public final class MobileValidationProto {
  private MobileValidationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mobile_SendCodeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mobile_SendCodeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mobile_SearchCodeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mobile_SearchCodeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mobile_SearchResultInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mobile_SearchResultInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mobile_SearchResultInfo_MapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mobile_SearchResultInfo_MapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mobile_CodeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mobile_CodeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mobile_SendCodeResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mobile_SendCodeResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mobile_ValidationCodeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mobile_ValidationCodeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mobile_ValidationResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mobile_ValidationResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035MobileValidationService.proto\022\006mobile\"" +
      "\254\001\n\014SendCodeInfo\022\016\n\006mobile\030\001 \001(\t\022\r\n\005toke" +
      "n\030\002 \001(\t\0227\n\014sendCodeType\030\003 \001(\0162!.mobile.S" +
      "endCodeInfo.SendCodeType\022\022\n\ncodeLength\030\004" +
      " \001(\005\"0\n\014SendCodeType\022\021\n\rSECURITY_CODE\020\000\022" +
      "\r\n\tMARKETING\020\001\"/\n\016SearchCodeInfo\022\016\n\006mobi" +
      "le\030\001 \001(\t\022\r\n\005token\030\002 \001(\t\"\257\001\n\020SearchResult" +
      "Info\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022\016\n\006m" +
      "obile\030\003 \001(\t\022.\n\003map\030\004 \003(\0132!.mobile.Search" +
      "ResultInfo.MapEntry\032<\n\010MapEntry\022\013\n\003key\030\001" +
      " \001(\t\022\037\n\005value\030\002 \001(\0132\020.mobile.CodeInfo:\0028" +
      "\001\"E\n\010CodeInfo\022\016\n\006status\030\001 \001(\010\022\026\n\016validat" +
      "ionCode\030\002 \001(\t\022\021\n\tsenderOrg\030\003 \001(\t\"h\n\016Send" +
      "CodeResult\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(" +
      "\t\022\016\n\006mobile\030\003 \001(\t\022\021\n\tcodeToken\030\004 \001(\t\022\024\n\014" +
      "sendPlatform\030\005 \001(\t\"Y\n\022ValidationCodeInfo" +
      "\022\021\n\tinputCode\030\001 \001(\t\022\021\n\tcodeToken\030\002 \001(\t\022\016" +
      "\n\006mobile\030\003 \001(\t\022\r\n\005token\030\004 \001(\t\"\201\001\n\020Valida" +
      "tionResult\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(" +
      "\t\022/\n\006status\030\003 \001(\0162\037.mobile.ValidationRes" +
      "ult.Status\"\035\n\006Status\022\007\n\003SUC\020\000\022\n\n\006FAILED\020" +
      "\0012\323\001\n\027MobileValidationSerivce\0226\n\004send\022\024." +
      "mobile.SendCodeInfo\032\026.mobile.SendCodeRes" +
      "ult\"\000\022B\n\010validate\022\032.mobile.ValidationCod" +
      "eInfo\032\030.mobile.ValidationResult\"\000\022<\n\006sea" +
      "rch\022\026.mobile.SearchCodeInfo\032\030.mobile.Sea" +
      "rchResultInfo\"\000BA\n&com.tianzhixing.auth." +
      "grpc.proto.mobileB\025MobileValidationProto" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_mobile_SendCodeInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mobile_SendCodeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mobile_SendCodeInfo_descriptor,
        new java.lang.String[] { "Mobile", "Token", "SendCodeType", "CodeLength", });
    internal_static_mobile_SearchCodeInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mobile_SearchCodeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mobile_SearchCodeInfo_descriptor,
        new java.lang.String[] { "Mobile", "Token", });
    internal_static_mobile_SearchResultInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_mobile_SearchResultInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mobile_SearchResultInfo_descriptor,
        new java.lang.String[] { "Code", "Message", "Mobile", "Map", });
    internal_static_mobile_SearchResultInfo_MapEntry_descriptor =
      internal_static_mobile_SearchResultInfo_descriptor.getNestedTypes().get(0);
    internal_static_mobile_SearchResultInfo_MapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mobile_SearchResultInfo_MapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mobile_CodeInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_mobile_CodeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mobile_CodeInfo_descriptor,
        new java.lang.String[] { "Status", "ValidationCode", "SenderOrg", });
    internal_static_mobile_SendCodeResult_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_mobile_SendCodeResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mobile_SendCodeResult_descriptor,
        new java.lang.String[] { "Code", "Message", "Mobile", "CodeToken", "SendPlatform", });
    internal_static_mobile_ValidationCodeInfo_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_mobile_ValidationCodeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mobile_ValidationCodeInfo_descriptor,
        new java.lang.String[] { "InputCode", "CodeToken", "Mobile", "Token", });
    internal_static_mobile_ValidationResult_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_mobile_ValidationResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mobile_ValidationResult_descriptor,
        new java.lang.String[] { "Code", "Message", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
