// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MobileValidationService.proto

package com.tianzhixing.auth.grpc.proto.mobile;

public interface SearchResultInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mobile.SearchResultInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *200成功，300业务错误
   * </pre>
   *
   * <code>int32 code = 1;</code>
   */
  int getCode();

  /**
   * <pre>
   *信息
   * </pre>
   *
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   *信息
   * </pre>
   *
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   *手机号
   * </pre>
   *
   * <code>string mobile = 3;</code>
   */
  java.lang.String getMobile();
  /**
   * <pre>
   *手机号
   * </pre>
   *
   * <code>string mobile = 3;</code>
   */
  com.google.protobuf.ByteString
      getMobileBytes();

  /**
   * <pre>
   *key = time, value = code info
   * </pre>
   *
   * <code>map&lt;string, .mobile.CodeInfo&gt; map = 4;</code>
   */
  int getMapCount();
  /**
   * <pre>
   *key = time, value = code info
   * </pre>
   *
   * <code>map&lt;string, .mobile.CodeInfo&gt; map = 4;</code>
   */
  boolean containsMap(
      java.lang.String key);
  /**
   * Use {@link #getMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.tianzhixing.auth.grpc.proto.mobile.CodeInfo>
  getMap();
  /**
   * <pre>
   *key = time, value = code info
   * </pre>
   *
   * <code>map&lt;string, .mobile.CodeInfo&gt; map = 4;</code>
   */
  java.util.Map<java.lang.String, com.tianzhixing.auth.grpc.proto.mobile.CodeInfo>
  getMapMap();
  /**
   * <pre>
   *key = time, value = code info
   * </pre>
   *
   * <code>map&lt;string, .mobile.CodeInfo&gt; map = 4;</code>
   */

  com.tianzhixing.auth.grpc.proto.mobile.CodeInfo getMapOrDefault(
      java.lang.String key,
      com.tianzhixing.auth.grpc.proto.mobile.CodeInfo defaultValue);
  /**
   * <pre>
   *key = time, value = code info
   * </pre>
   *
   * <code>map&lt;string, .mobile.CodeInfo&gt; map = 4;</code>
   */

  com.tianzhixing.auth.grpc.proto.mobile.CodeInfo getMapOrThrow(
      java.lang.String key);
}
