// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account_starpoint.proto

package com.tianzhixing.kernel.grpc.proto.account.starpoint;

/**
 * <pre>
 *排行查询信息
 * </pre>
 *
 * Protobuf type {@code account.starpoint.RankingInfo}
 */
public  final class RankingInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:account.starpoint.RankingInfo)
    RankingInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RankingInfo.newBuilder() to construct.
  private RankingInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RankingInfo() {
    token_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RankingInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper.Builder subBuilder = null;
            if (pageMapper_ != null) {
              subBuilder = pageMapper_.toBuilder();
            }
            pageMapper_ = input.readMessage(com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pageMapper_);
              pageMapper_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            token_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tianzhixing.kernel.grpc.proto.account.starpoint.AccountStarPointServiceProto.internal_static_account_starpoint_RankingInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tianzhixing.kernel.grpc.proto.account.starpoint.AccountStarPointServiceProto.internal_static_account_starpoint_RankingInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo.class, com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo.Builder.class);
  }

  public static final int PAGEMAPPER_FIELD_NUMBER = 1;
  private com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper pageMapper_;
  /**
   * <pre>
   *分页信息 必填
   * </pre>
   *
   * <code>.account.starpoint.PageMapper pageMapper = 1;</code>
   */
  public boolean hasPageMapper() {
    return pageMapper_ != null;
  }
  /**
   * <pre>
   *分页信息 必填
   * </pre>
   *
   * <code>.account.starpoint.PageMapper pageMapper = 1;</code>
   */
  public com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper getPageMapper() {
    return pageMapper_ == null ? com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper.getDefaultInstance() : pageMapper_;
  }
  /**
   * <pre>
   *分页信息 必填
   * </pre>
   *
   * <code>.account.starpoint.PageMapper pageMapper = 1;</code>
   */
  public com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapperOrBuilder getPageMapperOrBuilder() {
    return getPageMapper();
  }

  public static final int TOKEN_FIELD_NUMBER = 2;
  private volatile java.lang.Object token_;
  /**
   * <pre>
   *安全校验码-必填
   * </pre>
   *
   * <code>string token = 2;</code>
   */
  public java.lang.String getToken() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      token_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *安全校验码-必填
   * </pre>
   *
   * <code>string token = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTokenBytes() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      token_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (pageMapper_ != null) {
      output.writeMessage(1, getPageMapper());
    }
    if (!getTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (pageMapper_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPageMapper());
    }
    if (!getTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo)) {
      return super.equals(obj);
    }
    com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo other = (com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo) obj;

    boolean result = true;
    result = result && (hasPageMapper() == other.hasPageMapper());
    if (hasPageMapper()) {
      result = result && getPageMapper()
          .equals(other.getPageMapper());
    }
    result = result && getToken()
        .equals(other.getToken());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPageMapper()) {
      hash = (37 * hash) + PAGEMAPPER_FIELD_NUMBER;
      hash = (53 * hash) + getPageMapper().hashCode();
    }
    hash = (37 * hash) + TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getToken().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *排行查询信息
   * </pre>
   *
   * Protobuf type {@code account.starpoint.RankingInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:account.starpoint.RankingInfo)
      com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tianzhixing.kernel.grpc.proto.account.starpoint.AccountStarPointServiceProto.internal_static_account_starpoint_RankingInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tianzhixing.kernel.grpc.proto.account.starpoint.AccountStarPointServiceProto.internal_static_account_starpoint_RankingInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo.class, com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo.Builder.class);
    }

    // Construct using com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (pageMapperBuilder_ == null) {
        pageMapper_ = null;
      } else {
        pageMapper_ = null;
        pageMapperBuilder_ = null;
      }
      token_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tianzhixing.kernel.grpc.proto.account.starpoint.AccountStarPointServiceProto.internal_static_account_starpoint_RankingInfo_descriptor;
    }

    @java.lang.Override
    public com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo getDefaultInstanceForType() {
      return com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo build() {
      com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo buildPartial() {
      com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo result = new com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo(this);
      if (pageMapperBuilder_ == null) {
        result.pageMapper_ = pageMapper_;
      } else {
        result.pageMapper_ = pageMapperBuilder_.build();
      }
      result.token_ = token_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo) {
        return mergeFrom((com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo other) {
      if (other == com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo.getDefaultInstance()) return this;
      if (other.hasPageMapper()) {
        mergePageMapper(other.getPageMapper());
      }
      if (!other.getToken().isEmpty()) {
        token_ = other.token_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper pageMapper_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper, com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper.Builder, com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapperOrBuilder> pageMapperBuilder_;
    /**
     * <pre>
     *分页信息 必填
     * </pre>
     *
     * <code>.account.starpoint.PageMapper pageMapper = 1;</code>
     */
    public boolean hasPageMapper() {
      return pageMapperBuilder_ != null || pageMapper_ != null;
    }
    /**
     * <pre>
     *分页信息 必填
     * </pre>
     *
     * <code>.account.starpoint.PageMapper pageMapper = 1;</code>
     */
    public com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper getPageMapper() {
      if (pageMapperBuilder_ == null) {
        return pageMapper_ == null ? com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper.getDefaultInstance() : pageMapper_;
      } else {
        return pageMapperBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *分页信息 必填
     * </pre>
     *
     * <code>.account.starpoint.PageMapper pageMapper = 1;</code>
     */
    public Builder setPageMapper(com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper value) {
      if (pageMapperBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pageMapper_ = value;
        onChanged();
      } else {
        pageMapperBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *分页信息 必填
     * </pre>
     *
     * <code>.account.starpoint.PageMapper pageMapper = 1;</code>
     */
    public Builder setPageMapper(
        com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper.Builder builderForValue) {
      if (pageMapperBuilder_ == null) {
        pageMapper_ = builderForValue.build();
        onChanged();
      } else {
        pageMapperBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *分页信息 必填
     * </pre>
     *
     * <code>.account.starpoint.PageMapper pageMapper = 1;</code>
     */
    public Builder mergePageMapper(com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper value) {
      if (pageMapperBuilder_ == null) {
        if (pageMapper_ != null) {
          pageMapper_ =
            com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper.newBuilder(pageMapper_).mergeFrom(value).buildPartial();
        } else {
          pageMapper_ = value;
        }
        onChanged();
      } else {
        pageMapperBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *分页信息 必填
     * </pre>
     *
     * <code>.account.starpoint.PageMapper pageMapper = 1;</code>
     */
    public Builder clearPageMapper() {
      if (pageMapperBuilder_ == null) {
        pageMapper_ = null;
        onChanged();
      } else {
        pageMapper_ = null;
        pageMapperBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *分页信息 必填
     * </pre>
     *
     * <code>.account.starpoint.PageMapper pageMapper = 1;</code>
     */
    public com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper.Builder getPageMapperBuilder() {
      
      onChanged();
      return getPageMapperFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *分页信息 必填
     * </pre>
     *
     * <code>.account.starpoint.PageMapper pageMapper = 1;</code>
     */
    public com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapperOrBuilder getPageMapperOrBuilder() {
      if (pageMapperBuilder_ != null) {
        return pageMapperBuilder_.getMessageOrBuilder();
      } else {
        return pageMapper_ == null ?
            com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper.getDefaultInstance() : pageMapper_;
      }
    }
    /**
     * <pre>
     *分页信息 必填
     * </pre>
     *
     * <code>.account.starpoint.PageMapper pageMapper = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper, com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper.Builder, com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapperOrBuilder> 
        getPageMapperFieldBuilder() {
      if (pageMapperBuilder_ == null) {
        pageMapperBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper, com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapper.Builder, com.tianzhixing.kernel.grpc.proto.account.starpoint.PageMapperOrBuilder>(
                getPageMapper(),
                getParentForChildren(),
                isClean());
        pageMapper_ = null;
      }
      return pageMapperBuilder_;
    }

    private java.lang.Object token_ = "";
    /**
     * <pre>
     *安全校验码-必填
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *安全校验码-必填
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *安全校验码-必填
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    public Builder setToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      token_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *安全校验码-必填
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    public Builder clearToken() {
      
      token_ = getDefaultInstance().getToken();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *安全校验码-必填
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    public Builder setTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      token_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:account.starpoint.RankingInfo)
  }

  // @@protoc_insertion_point(class_scope:account.starpoint.RankingInfo)
  private static final com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo();
  }

  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RankingInfo>
      PARSER = new com.google.protobuf.AbstractParser<RankingInfo>() {
    @java.lang.Override
    public RankingInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RankingInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RankingInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RankingInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tianzhixing.kernel.grpc.proto.account.starpoint.RankingInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

