// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account_starpoint.proto

package com.tianzhixing.kernel.grpc.proto.account.starpoint;

/**
 * <pre>
 *未采集星点详情
 * </pre>
 *
 * Protobuf type {@code account.starpoint.UnCollectionRecordsInfo}
 */
public  final class UnCollectionRecordsInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:account.starpoint.UnCollectionRecordsInfo)
    UnCollectionRecordsInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UnCollectionRecordsInfo.newBuilder() to construct.
  private UnCollectionRecordsInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UnCollectionRecordsInfo() {
    operStarPoint_ = "";
    longitudeAndLatitude_ = "";
    recordsType_ = "";
    taskId_ = "";
    advertisementId_ = "";
    remark_ = "";
    createTime_ = 0L;
    recordToken_ = "";
    overdueTime_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UnCollectionRecordsInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            operStarPoint_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            longitudeAndLatitude_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            recordsType_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            taskId_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            advertisementId_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            remark_ = s;
            break;
          }
          case 56: {

            createTime_ = input.readInt64();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            recordToken_ = s;
            break;
          }
          case 72: {

            overdueTime_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tianzhixing.kernel.grpc.proto.account.starpoint.AccountStarPointServiceProto.internal_static_account_starpoint_UnCollectionRecordsInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tianzhixing.kernel.grpc.proto.account.starpoint.AccountStarPointServiceProto.internal_static_account_starpoint_UnCollectionRecordsInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo.class, com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo.Builder.class);
  }

  public static final int OPERSTARPOINT_FIELD_NUMBER = 1;
  private volatile java.lang.Object operStarPoint_;
  /**
   * <pre>
   *操作星点数
   * </pre>
   *
   * <code>string operStarPoint = 1;</code>
   */
  public java.lang.String getOperStarPoint() {
    java.lang.Object ref = operStarPoint_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      operStarPoint_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *操作星点数
   * </pre>
   *
   * <code>string operStarPoint = 1;</code>
   */
  public com.google.protobuf.ByteString
      getOperStarPointBytes() {
    java.lang.Object ref = operStarPoint_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      operStarPoint_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LONGITUDEANDLATITUDE_FIELD_NUMBER = 2;
  private volatile java.lang.Object longitudeAndLatitude_;
  /**
   * <pre>
   *经纬度
   * </pre>
   *
   * <code>string longitudeAndLatitude = 2;</code>
   */
  public java.lang.String getLongitudeAndLatitude() {
    java.lang.Object ref = longitudeAndLatitude_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      longitudeAndLatitude_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *经纬度
   * </pre>
   *
   * <code>string longitudeAndLatitude = 2;</code>
   */
  public com.google.protobuf.ByteString
      getLongitudeAndLatitudeBytes() {
    java.lang.Object ref = longitudeAndLatitude_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      longitudeAndLatitude_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECORDSTYPE_FIELD_NUMBER = 3;
  private volatile java.lang.Object recordsType_;
  /**
   * <pre>
   *记录类型(TASK，RANDOM)
   * </pre>
   *
   * <code>string recordsType = 3;</code>
   */
  public java.lang.String getRecordsType() {
    java.lang.Object ref = recordsType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      recordsType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *记录类型(TASK，RANDOM)
   * </pre>
   *
   * <code>string recordsType = 3;</code>
   */
  public com.google.protobuf.ByteString
      getRecordsTypeBytes() {
    java.lang.Object ref = recordsType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      recordsType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TASKID_FIELD_NUMBER = 4;
  private volatile java.lang.Object taskId_;
  /**
   * <pre>
   *任务ID
   * </pre>
   *
   * <code>string taskId = 4;</code>
   */
  public java.lang.String getTaskId() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      taskId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *任务ID
   * </pre>
   *
   * <code>string taskId = 4;</code>
   */
  public com.google.protobuf.ByteString
      getTaskIdBytes() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taskId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADVERTISEMENTID_FIELD_NUMBER = 5;
  private volatile java.lang.Object advertisementId_;
  /**
   * <pre>
   *广告ID
   * </pre>
   *
   * <code>string advertisementId = 5;</code>
   */
  public java.lang.String getAdvertisementId() {
    java.lang.Object ref = advertisementId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      advertisementId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *广告ID
   * </pre>
   *
   * <code>string advertisementId = 5;</code>
   */
  public com.google.protobuf.ByteString
      getAdvertisementIdBytes() {
    java.lang.Object ref = advertisementId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      advertisementId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REMARK_FIELD_NUMBER = 6;
  private volatile java.lang.Object remark_;
  /**
   * <pre>
   *备注
   * </pre>
   *
   * <code>string remark = 6;</code>
   */
  public java.lang.String getRemark() {
    java.lang.Object ref = remark_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      remark_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *备注
   * </pre>
   *
   * <code>string remark = 6;</code>
   */
  public com.google.protobuf.ByteString
      getRemarkBytes() {
    java.lang.Object ref = remark_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      remark_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATETIME_FIELD_NUMBER = 7;
  private long createTime_;
  /**
   * <pre>
   *创建时间
   * </pre>
   *
   * <code>int64 createTime = 7;</code>
   */
  public long getCreateTime() {
    return createTime_;
  }

  public static final int RECORDTOKEN_FIELD_NUMBER = 8;
  private volatile java.lang.Object recordToken_;
  /**
   * <pre>
   *记录token
   * </pre>
   *
   * <code>string recordToken = 8;</code>
   */
  public java.lang.String getRecordToken() {
    java.lang.Object ref = recordToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      recordToken_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *记录token
   * </pre>
   *
   * <code>string recordToken = 8;</code>
   */
  public com.google.protobuf.ByteString
      getRecordTokenBytes() {
    java.lang.Object ref = recordToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      recordToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OVERDUETIME_FIELD_NUMBER = 9;
  private long overdueTime_;
  /**
   * <pre>
   *到期时间
   * </pre>
   *
   * <code>int64 overdueTime = 9;</code>
   */
  public long getOverdueTime() {
    return overdueTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getOperStarPointBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, operStarPoint_);
    }
    if (!getLongitudeAndLatitudeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, longitudeAndLatitude_);
    }
    if (!getRecordsTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, recordsType_);
    }
    if (!getTaskIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, taskId_);
    }
    if (!getAdvertisementIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, advertisementId_);
    }
    if (!getRemarkBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, remark_);
    }
    if (createTime_ != 0L) {
      output.writeInt64(7, createTime_);
    }
    if (!getRecordTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, recordToken_);
    }
    if (overdueTime_ != 0L) {
      output.writeInt64(9, overdueTime_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getOperStarPointBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, operStarPoint_);
    }
    if (!getLongitudeAndLatitudeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, longitudeAndLatitude_);
    }
    if (!getRecordsTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, recordsType_);
    }
    if (!getTaskIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, taskId_);
    }
    if (!getAdvertisementIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, advertisementId_);
    }
    if (!getRemarkBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, remark_);
    }
    if (createTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, createTime_);
    }
    if (!getRecordTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, recordToken_);
    }
    if (overdueTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, overdueTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo)) {
      return super.equals(obj);
    }
    com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo other = (com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo) obj;

    boolean result = true;
    result = result && getOperStarPoint()
        .equals(other.getOperStarPoint());
    result = result && getLongitudeAndLatitude()
        .equals(other.getLongitudeAndLatitude());
    result = result && getRecordsType()
        .equals(other.getRecordsType());
    result = result && getTaskId()
        .equals(other.getTaskId());
    result = result && getAdvertisementId()
        .equals(other.getAdvertisementId());
    result = result && getRemark()
        .equals(other.getRemark());
    result = result && (getCreateTime()
        == other.getCreateTime());
    result = result && getRecordToken()
        .equals(other.getRecordToken());
    result = result && (getOverdueTime()
        == other.getOverdueTime());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OPERSTARPOINT_FIELD_NUMBER;
    hash = (53 * hash) + getOperStarPoint().hashCode();
    hash = (37 * hash) + LONGITUDEANDLATITUDE_FIELD_NUMBER;
    hash = (53 * hash) + getLongitudeAndLatitude().hashCode();
    hash = (37 * hash) + RECORDSTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getRecordsType().hashCode();
    hash = (37 * hash) + TASKID_FIELD_NUMBER;
    hash = (53 * hash) + getTaskId().hashCode();
    hash = (37 * hash) + ADVERTISEMENTID_FIELD_NUMBER;
    hash = (53 * hash) + getAdvertisementId().hashCode();
    hash = (37 * hash) + REMARK_FIELD_NUMBER;
    hash = (53 * hash) + getRemark().hashCode();
    hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreateTime());
    hash = (37 * hash) + RECORDTOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getRecordToken().hashCode();
    hash = (37 * hash) + OVERDUETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOverdueTime());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *未采集星点详情
   * </pre>
   *
   * Protobuf type {@code account.starpoint.UnCollectionRecordsInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:account.starpoint.UnCollectionRecordsInfo)
      com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tianzhixing.kernel.grpc.proto.account.starpoint.AccountStarPointServiceProto.internal_static_account_starpoint_UnCollectionRecordsInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tianzhixing.kernel.grpc.proto.account.starpoint.AccountStarPointServiceProto.internal_static_account_starpoint_UnCollectionRecordsInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo.class, com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo.Builder.class);
    }

    // Construct using com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      operStarPoint_ = "";

      longitudeAndLatitude_ = "";

      recordsType_ = "";

      taskId_ = "";

      advertisementId_ = "";

      remark_ = "";

      createTime_ = 0L;

      recordToken_ = "";

      overdueTime_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tianzhixing.kernel.grpc.proto.account.starpoint.AccountStarPointServiceProto.internal_static_account_starpoint_UnCollectionRecordsInfo_descriptor;
    }

    @java.lang.Override
    public com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo getDefaultInstanceForType() {
      return com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo build() {
      com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo buildPartial() {
      com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo result = new com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo(this);
      result.operStarPoint_ = operStarPoint_;
      result.longitudeAndLatitude_ = longitudeAndLatitude_;
      result.recordsType_ = recordsType_;
      result.taskId_ = taskId_;
      result.advertisementId_ = advertisementId_;
      result.remark_ = remark_;
      result.createTime_ = createTime_;
      result.recordToken_ = recordToken_;
      result.overdueTime_ = overdueTime_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo) {
        return mergeFrom((com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo other) {
      if (other == com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo.getDefaultInstance()) return this;
      if (!other.getOperStarPoint().isEmpty()) {
        operStarPoint_ = other.operStarPoint_;
        onChanged();
      }
      if (!other.getLongitudeAndLatitude().isEmpty()) {
        longitudeAndLatitude_ = other.longitudeAndLatitude_;
        onChanged();
      }
      if (!other.getRecordsType().isEmpty()) {
        recordsType_ = other.recordsType_;
        onChanged();
      }
      if (!other.getTaskId().isEmpty()) {
        taskId_ = other.taskId_;
        onChanged();
      }
      if (!other.getAdvertisementId().isEmpty()) {
        advertisementId_ = other.advertisementId_;
        onChanged();
      }
      if (!other.getRemark().isEmpty()) {
        remark_ = other.remark_;
        onChanged();
      }
      if (other.getCreateTime() != 0L) {
        setCreateTime(other.getCreateTime());
      }
      if (!other.getRecordToken().isEmpty()) {
        recordToken_ = other.recordToken_;
        onChanged();
      }
      if (other.getOverdueTime() != 0L) {
        setOverdueTime(other.getOverdueTime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object operStarPoint_ = "";
    /**
     * <pre>
     *操作星点数
     * </pre>
     *
     * <code>string operStarPoint = 1;</code>
     */
    public java.lang.String getOperStarPoint() {
      java.lang.Object ref = operStarPoint_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operStarPoint_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *操作星点数
     * </pre>
     *
     * <code>string operStarPoint = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOperStarPointBytes() {
      java.lang.Object ref = operStarPoint_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operStarPoint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *操作星点数
     * </pre>
     *
     * <code>string operStarPoint = 1;</code>
     */
    public Builder setOperStarPoint(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      operStarPoint_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *操作星点数
     * </pre>
     *
     * <code>string operStarPoint = 1;</code>
     */
    public Builder clearOperStarPoint() {
      
      operStarPoint_ = getDefaultInstance().getOperStarPoint();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *操作星点数
     * </pre>
     *
     * <code>string operStarPoint = 1;</code>
     */
    public Builder setOperStarPointBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      operStarPoint_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object longitudeAndLatitude_ = "";
    /**
     * <pre>
     *经纬度
     * </pre>
     *
     * <code>string longitudeAndLatitude = 2;</code>
     */
    public java.lang.String getLongitudeAndLatitude() {
      java.lang.Object ref = longitudeAndLatitude_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        longitudeAndLatitude_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *经纬度
     * </pre>
     *
     * <code>string longitudeAndLatitude = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLongitudeAndLatitudeBytes() {
      java.lang.Object ref = longitudeAndLatitude_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        longitudeAndLatitude_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *经纬度
     * </pre>
     *
     * <code>string longitudeAndLatitude = 2;</code>
     */
    public Builder setLongitudeAndLatitude(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      longitudeAndLatitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *经纬度
     * </pre>
     *
     * <code>string longitudeAndLatitude = 2;</code>
     */
    public Builder clearLongitudeAndLatitude() {
      
      longitudeAndLatitude_ = getDefaultInstance().getLongitudeAndLatitude();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *经纬度
     * </pre>
     *
     * <code>string longitudeAndLatitude = 2;</code>
     */
    public Builder setLongitudeAndLatitudeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      longitudeAndLatitude_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object recordsType_ = "";
    /**
     * <pre>
     *记录类型(TASK，RANDOM)
     * </pre>
     *
     * <code>string recordsType = 3;</code>
     */
    public java.lang.String getRecordsType() {
      java.lang.Object ref = recordsType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recordsType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *记录类型(TASK，RANDOM)
     * </pre>
     *
     * <code>string recordsType = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRecordsTypeBytes() {
      java.lang.Object ref = recordsType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recordsType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *记录类型(TASK，RANDOM)
     * </pre>
     *
     * <code>string recordsType = 3;</code>
     */
    public Builder setRecordsType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      recordsType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *记录类型(TASK，RANDOM)
     * </pre>
     *
     * <code>string recordsType = 3;</code>
     */
    public Builder clearRecordsType() {
      
      recordsType_ = getDefaultInstance().getRecordsType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *记录类型(TASK，RANDOM)
     * </pre>
     *
     * <code>string recordsType = 3;</code>
     */
    public Builder setRecordsTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      recordsType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object taskId_ = "";
    /**
     * <pre>
     *任务ID
     * </pre>
     *
     * <code>string taskId = 4;</code>
     */
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *任务ID
     * </pre>
     *
     * <code>string taskId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *任务ID
     * </pre>
     *
     * <code>string taskId = 4;</code>
     */
    public Builder setTaskId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      taskId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *任务ID
     * </pre>
     *
     * <code>string taskId = 4;</code>
     */
    public Builder clearTaskId() {
      
      taskId_ = getDefaultInstance().getTaskId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *任务ID
     * </pre>
     *
     * <code>string taskId = 4;</code>
     */
    public Builder setTaskIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      taskId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object advertisementId_ = "";
    /**
     * <pre>
     *广告ID
     * </pre>
     *
     * <code>string advertisementId = 5;</code>
     */
    public java.lang.String getAdvertisementId() {
      java.lang.Object ref = advertisementId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        advertisementId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *广告ID
     * </pre>
     *
     * <code>string advertisementId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAdvertisementIdBytes() {
      java.lang.Object ref = advertisementId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        advertisementId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *广告ID
     * </pre>
     *
     * <code>string advertisementId = 5;</code>
     */
    public Builder setAdvertisementId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      advertisementId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *广告ID
     * </pre>
     *
     * <code>string advertisementId = 5;</code>
     */
    public Builder clearAdvertisementId() {
      
      advertisementId_ = getDefaultInstance().getAdvertisementId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *广告ID
     * </pre>
     *
     * <code>string advertisementId = 5;</code>
     */
    public Builder setAdvertisementIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      advertisementId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object remark_ = "";
    /**
     * <pre>
     *备注
     * </pre>
     *
     * <code>string remark = 6;</code>
     */
    public java.lang.String getRemark() {
      java.lang.Object ref = remark_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        remark_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *备注
     * </pre>
     *
     * <code>string remark = 6;</code>
     */
    public com.google.protobuf.ByteString
        getRemarkBytes() {
      java.lang.Object ref = remark_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *备注
     * </pre>
     *
     * <code>string remark = 6;</code>
     */
    public Builder setRemark(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      remark_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *备注
     * </pre>
     *
     * <code>string remark = 6;</code>
     */
    public Builder clearRemark() {
      
      remark_ = getDefaultInstance().getRemark();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *备注
     * </pre>
     *
     * <code>string remark = 6;</code>
     */
    public Builder setRemarkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      remark_ = value;
      onChanged();
      return this;
    }

    private long createTime_ ;
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>int64 createTime = 7;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>int64 createTime = 7;</code>
     */
    public Builder setCreateTime(long value) {
      
      createTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>int64 createTime = 7;</code>
     */
    public Builder clearCreateTime() {
      
      createTime_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object recordToken_ = "";
    /**
     * <pre>
     *记录token
     * </pre>
     *
     * <code>string recordToken = 8;</code>
     */
    public java.lang.String getRecordToken() {
      java.lang.Object ref = recordToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recordToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *记录token
     * </pre>
     *
     * <code>string recordToken = 8;</code>
     */
    public com.google.protobuf.ByteString
        getRecordTokenBytes() {
      java.lang.Object ref = recordToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recordToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *记录token
     * </pre>
     *
     * <code>string recordToken = 8;</code>
     */
    public Builder setRecordToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      recordToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *记录token
     * </pre>
     *
     * <code>string recordToken = 8;</code>
     */
    public Builder clearRecordToken() {
      
      recordToken_ = getDefaultInstance().getRecordToken();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *记录token
     * </pre>
     *
     * <code>string recordToken = 8;</code>
     */
    public Builder setRecordTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      recordToken_ = value;
      onChanged();
      return this;
    }

    private long overdueTime_ ;
    /**
     * <pre>
     *到期时间
     * </pre>
     *
     * <code>int64 overdueTime = 9;</code>
     */
    public long getOverdueTime() {
      return overdueTime_;
    }
    /**
     * <pre>
     *到期时间
     * </pre>
     *
     * <code>int64 overdueTime = 9;</code>
     */
    public Builder setOverdueTime(long value) {
      
      overdueTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *到期时间
     * </pre>
     *
     * <code>int64 overdueTime = 9;</code>
     */
    public Builder clearOverdueTime() {
      
      overdueTime_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:account.starpoint.UnCollectionRecordsInfo)
  }

  // @@protoc_insertion_point(class_scope:account.starpoint.UnCollectionRecordsInfo)
  private static final com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo();
  }

  public static com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UnCollectionRecordsInfo>
      PARSER = new com.google.protobuf.AbstractParser<UnCollectionRecordsInfo>() {
    @java.lang.Override
    public UnCollectionRecordsInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UnCollectionRecordsInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UnCollectionRecordsInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UnCollectionRecordsInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tianzhixing.kernel.grpc.proto.account.starpoint.UnCollectionRecordsInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

