// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device_operation.proto

package com.tianzhixing.kernel.grpc.proto.device.operation;

public final class DeviceOperationServiceProto {
  private DeviceOperationServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_device_operation_DeviceInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_device_operation_DeviceInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_device_operation_Result_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_device_operation_Result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026device_operation.proto\022\020device.operati" +
      "on\032\025response_entity.proto\"\226\001\n\nDeviceInfo" +
      "\022\024\n\014accountToken\030\001 \001(\t\022\r\n\005token\030\002 \001(\t\022\020\n" +
      "\010deviceId\030\003 \001(\t\022\022\n\ndeviceType\030\004 \001(\t\022\021\n\td" +
      "eviceMAC\030\005 \001(\t\022\023\n\013deviceModel\030\006 \001(\t\022\025\n\ro" +
      "perationTime\030\007 \001(\003\"1\n\006Result\022\'\n\016response" +
      "Entity\030\001 \001(\0132\017.ResponseEntity2\236\001\n\026Device" +
      "OperationService\022@\n\004bind\022\034.device.operat" +
      "ion.DeviceInfo\032\030.device.operation.Result" +
      "\"\000\022B\n\006unBind\022\034.device.operation.DeviceIn" +
      "fo\032\030.device.operation.Result\"\000BS\n2com.ti" +
      "anzhixing.kernel.grpc.proto.device.opera" +
      "tionB\033DeviceOperationServiceProtoP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tianzhixing.kernel.grpc.proto.ResponseEntityProto.getDescriptor(),
        }, assigner);
    internal_static_device_operation_DeviceInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_device_operation_DeviceInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_device_operation_DeviceInfo_descriptor,
        new java.lang.String[] { "AccountToken", "Token", "DeviceId", "DeviceType", "DeviceMAC", "DeviceModel", "OperationTime", });
    internal_static_device_operation_Result_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_device_operation_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_device_operation_Result_descriptor,
        new java.lang.String[] { "ResponseEntity", });
    com.tianzhixing.kernel.grpc.proto.ResponseEntityProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
