// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account_starpoint_operation.proto

package com.tianzhixing.kernel.grpc.proto.account.starpoint.operation;

public interface AwardInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:account.starpoint.operation.AwardInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *需存储的第三方唯一token 必填
   * </pre>
   *
   * <code>string accountToken = 1;</code>
   */
  java.lang.String getAccountToken();
  /**
   * <pre>
   *需存储的第三方唯一token 必填
   * </pre>
   *
   * <code>string accountToken = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccountTokenBytes();

  /**
   * <pre>
   *安全校验码-必填
   * </pre>
   *
   * <code>string token = 2;</code>
   */
  java.lang.String getToken();
  /**
   * <pre>
   *安全校验码-必填
   * </pre>
   *
   * <code>string token = 2;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <pre>
   *奖励时间
   * </pre>
   *
   * <code>int64 adwardTime = 3;</code>
   */
  long getAdwardTime();

  /**
   * <pre>
   *奖励类型
   * </pre>
   *
   * <code>string adwardType = 4;</code>
   */
  java.lang.String getAdwardType();
  /**
   * <pre>
   *奖励类型
   * </pre>
   *
   * <code>string adwardType = 4;</code>
   */
  com.google.protobuf.ByteString
      getAdwardTypeBytes();
}
