// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account_starpoint_operation.proto

package com.tianzhixing.kernel.grpc.proto.account.starpoint.operation;

public interface StarPointRecordsInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:account.starpoint.operation.StarPointRecordsInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *记录token - 必填
   * </pre>
   *
   * <code>string recordToken = 1;</code>
   */
  java.lang.String getRecordToken();
  /**
   * <pre>
   *记录token - 必填
   * </pre>
   *
   * <code>string recordToken = 1;</code>
   */
  com.google.protobuf.ByteString
      getRecordTokenBytes();
}
