// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account_reg.proto

package com.tianzhixing.kernel.grpc.proto.account.reg;

public interface CheckMobileInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:account.reg.CheckMobileInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *手机号码-必填
   * </pre>
   *
   * <code>string mobile = 1;</code>
   */
  java.lang.String getMobile();
  /**
   * <pre>
   *手机号码-必填
   * </pre>
   *
   * <code>string mobile = 1;</code>
   */
  com.google.protobuf.ByteString
      getMobileBytes();

  /**
   * <pre>
   *安全校验码-必填
   * </pre>
   *
   * <code>string token = 2;</code>
   */
  java.lang.String getToken();
  /**
   * <pre>
   *安全校验码-必填
   * </pre>
   *
   * <code>string token = 2;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <pre>
   *机构 - 必填
   * </pre>
   *
   * <code>string org = 3;</code>
   */
  java.lang.String getOrg();
  /**
   * <pre>
   *机构 - 必填
   * </pre>
   *
   * <code>string org = 3;</code>
   */
  com.google.protobuf.ByteString
      getOrgBytes();
}
