platform :ios, '8.0'

target 'starChain' do

pod 'AFNetworking', '~> 3.2.1'
pod 'Masonry'
pod 'SDCycleScrollView'
pod 'SDWebImage', '~> 3.8.1'
pod 'MJRefresh'
pod 'Bugly', '~> 2.5.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'MJExtension'
pod 'BaiduMapKit'
pod 'UMCCommon'
pod 'UMCSecurityPlugins'
pod 'UMCCommonLog'
pod 'UMCShare/Social/ReducedSina'
pod 'UMCShare/Social/ReducedWeChat'

 

end
